# Generated by Django 4.2.7 on 2025-02-02 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BANK", "Bank"), ("CREDIT_UNION", "Credit Union")],
                        max_length=20,
                    ),
                ),
                ("charter_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "web_domain",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuarterlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("total_assets", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "total_deposits",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_stats",
                        to="prospects.financialinstitution",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="financialinstitution",
            index=models.Index(fields=["type"], name="prospects_f_type_5a993d_idx"),
        ),
        migrations.AddIndex(
            model_name="financialinstitution",
            index=models.Index(
                fields=["charter_number"], name="prospects_f_charter_086848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialinstitution",
            index=models.Index(
                fields=["web_domain"], name="prospects_f_web_dom_606019_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialinstitution",
            index=models.Index(fields=["state"], name="prospects_f_state_154332_idx"),
        ),
        migrations.AddIndex(
            model_name="quarterlystats",
            index=models.Index(
                fields=["year", "quarter"], name="prospects_q_year_63cf79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarterlystats",
            index=models.Index(
                fields=["total_assets"], name="prospects_q_total_a_cd5a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarterlystats",
            index=models.Index(
                fields=["total_deposits"], name="prospects_q_total_d_43e38d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quarterlystats",
            unique_together={("institution", "year", "quarter")},
        ),
    ]
