# Generated by Django 4.2.7 on 2025-02-02 11:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialinstitution",
            options={"ordering": ["charter_number"]},
        ),
        migrations.AlterModelOptions(
            name="quarterlystats",
            options={"ordering": ["-quarter_end_date"]},
        ),
        migrations.RemoveIndex(
            model_name="financialinstitution",
            name="prospects_f_type_5a993d_idx",
        ),
        migrations.RemoveIndex(
            model_name="financialinstitution",
            name="prospects_f_charter_086848_idx",
        ),
        migrations.RemoveIndex(
            model_name="financialinstitution",
            name="prospects_f_web_dom_606019_idx",
        ),
        migrations.RemoveIndex(
            model_name="quarterlystats",
            name="prospects_q_year_63cf79_idx",
        ),
        migrations.RemoveIndex(
            model_name="quarterlystats",
            name="prospects_q_total_a_cd5a74_idx",
        ),
        migrations.RemoveIndex(
            model_name="quarterlystats",
            name="prospects_q_total_d_43e38d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="quarterlystats",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="financialinstitution",
            name="name",
        ),
        migrations.RemoveField(
            model_name="financialinstitution",
            name="type",
        ),
        migrations.AddField(
            model_name="financialinstitution",
            name="asset_tier",
            field=models.CharField(
                choices=[
                    ("<$100M", "Less than $100M"),
                    ("$100M-$500M", "$100M to $500M"),
                    ("$500M-$1B", "$500M to $1B"),
                    ("$1B-$10B", "$1B to $10B"),
                    (">$10B", "Greater than $10B"),
                ],
                default=django.utils.timezone.now,
                help_text="Asset size category",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financialinstitution",
            name="institution_type",
            field=models.CharField(
                choices=[("BANK", "Bank"), ("CREDIT_UNION", "Credit Union")],
                default=django.utils.timezone.now,
                help_text="Type of financial institution",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quarterlystats",
            name="deposit_change_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage change in deposits from previous quarter",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlystats",
            name="quarter_end_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="End date of the quarter"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financialinstitution",
            name="charter_number",
            field=models.CharField(
                help_text="Unique charter number assigned by regulator",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="financialinstitution",
            name="city",
            field=models.CharField(
                help_text="City where the institution is located", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="financialinstitution",
            name="state",
            field=models.CharField(help_text="Two-letter state code", max_length=2),
        ),
        migrations.AlterField(
            model_name="financialinstitution",
            name="web_domain",
            field=models.CharField(
                blank=True,
                help_text="Primary web domain of the institution",
                max_length=255,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="quarterlystats",
            name="total_assets",
            field=models.DecimalField(
                decimal_places=2, help_text="Total assets in dollars", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="quarterlystats",
            name="total_deposits",
            field=models.DecimalField(
                decimal_places=2, help_text="Total deposits in dollars", max_digits=14
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quarterlystats",
            unique_together={("institution", "quarter_end_date")},
        ),
        migrations.AddIndex(
            model_name="financialinstitution",
            index=models.Index(
                fields=["institution_type"], name="prospects_f_institu_d492c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialinstitution",
            index=models.Index(
                fields=["asset_tier"], name="prospects_f_asset_t_033e83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarterlystats",
            index=models.Index(
                fields=["quarter_end_date"], name="prospects_q_quarter_dd9ac7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarterlystats",
            index=models.Index(
                fields=["deposit_change_pct"], name="prospects_q_deposit_c39a5c_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="quarterlystats",
            name="quarter",
        ),
        migrations.RemoveField(
            model_name="quarterlystats",
            name="year",
        ),
    ]
