# Generated by Django 4.2.7 on 2025-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0002_alter_financialinstitution_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinstitution",
            name="asset_tier",
            field=models.CharField(
                choices=[
                    ("<$100M", "Less than $100M"),
                    ("$100M-$500M", "$100M to $500M"),
                    ("$500M-$1B", "$500M to $1B"),
                    ("$1B-$10B", "$1B to $10B"),
                    (">$10B", "Greater than $10B"),
                ],
                default="<$100M",
                help_text="Asset size category",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialinstitution",
            name="institution_type",
            field=models.CharField(
                choices=[("BANK", "Bank"), ("CREDIT_UNION", "Credit Union")],
                default="BANK",
                help_text="Type of financial institution",
                max_length=20,
            ),
        ),
    ]
